/*
 * TurboVec on SPCS - Setup Script
 * Run this in Snowsight or SnowSQL to set up the environment
 */

-- ============================================================
-- 1. ACCOUNT-LEVEL SETUP (requires ACCOUNTADMIN)
-- ============================================================
USE ROLE ACCOUNTADMIN;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN;

-- External access for notebook to download sample data
CREATE OR REPLACE NETWORK RULE turbovec_egress_rule
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION turbovec_eai
  ALLOWED_NETWORK_RULES = (turbovec_egress_rule)
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION turbovec_eai TO ROLE SYSADMIN;

-- ============================================================
-- 2. ROLE & USER SETUP (requires SECURITYADMIN / USERADMIN)
-- ============================================================
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS TURBOVEC_ROLE;

USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS turbovec_user
  PASSWORD = 'TurboVec2026!'
  DEFAULT_ROLE = TURBOVEC_ROLE
  DEFAULT_SECONDARY_ROLES = ('ALL')
  MUST_CHANGE_PASSWORD = FALSE;

USE ROLE SECURITYADMIN;
GRANT ROLE TURBOVEC_ROLE TO USER turbovec_user;

-- ============================================================
-- 3. DATABASE, WAREHOUSE, STAGES (requires SYSADMIN)
-- ============================================================
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE TURBOVEC_WAREHOUSE WITH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 180
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS TURBOVEC_DEMO;
USE DATABASE TURBOVEC_DEMO;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE IMAGE REPOSITORY IF NOT EXISTS TURBOVEC_DEMO.PUBLIC.TURBOVEC_REPO;

CREATE OR REPLACE STAGE YAML_STAGE;
CREATE OR REPLACE STAGE DATA ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE OR REPLACE STAGE INDEXES ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- ============================================================
-- 4. GRANTS
-- ============================================================
USE ROLE SECURITYADMIN;
GRANT ALL PRIVILEGES ON DATABASE TURBOVEC_DEMO TO ROLE TURBOVEC_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA TURBOVEC_DEMO.PUBLIC TO ROLE TURBOVEC_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE TURBOVEC_WAREHOUSE TO ROLE TURBOVEC_ROLE;
GRANT ALL PRIVILEGES ON STAGE TURBOVEC_DEMO.PUBLIC.DATA TO ROLE TURBOVEC_ROLE;
GRANT ALL PRIVILEGES ON STAGE TURBOVEC_DEMO.PUBLIC.INDEXES TO ROLE TURBOVEC_ROLE;

-- ============================================================
-- 5. COMPUTE POOLS
-- ============================================================
USE ROLE SYSADMIN;

CREATE COMPUTE POOL IF NOT EXISTS TURBOVEC_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = TRUE;

CREATE COMPUTE POOL IF NOT EXISTS JUPYTER_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = TRUE;

-- Check status
DESCRIBE COMPUTE POOL TURBOVEC_COMPUTE_POOL;
DESCRIBE COMPUTE POOL JUPYTER_COMPUTE_POOL;
